-- Seed data for Supabase (PostgreSQL)
-- Safe to run multiple times thanks to ON CONFLICT DO UPDATE.
-- Assumes tables:
--   public.speakers(id, name, role, company, bio, photo_url, social_links)
--   public.sessions(id, title, description, start_time, end_time, duration, room, day, track, type, level, speaker_ids, capacity, registered, tags, livestream_url, slides_url, updated_at)

insert into public.speakers (id, name, role, company, bio, photo_url, social_links)
values
  (
    'spk-sara-chen',
    'Sara Chen',
    'Staff ML Engineer',
    'Google',
    'Works on multimodal models and production ML systems.',
    'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    '{"x":"https://x.com/sarachen","linkedin":"https://linkedin.com/in/sarachen"}'::jsonb
  ),
  (
    'spk-miguel-ortiz',
    'Miguel Ortiz',
    'Android Developer Advocate',
    'Google',
    'Focuses on modern Android architecture and performance.',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    '{"x":"https://x.com/miguelortiz","github":"https://github.com/miguelortiz"}'::jsonb
  ),
  (
    'spk-priya-nair',
    'Priya Nair',
    'Product Manager',
    'Firebase',
    'Leads developer platform features and realtime tooling.',
    'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f',
    '{"linkedin":"https://linkedin.com/in/priyanair"}'::jsonb
  ),
  (
    'spk-luca-bianchi',
    'Luca Bianchi',
    'Cloud Architect',
    'Google Cloud',
    'Designs scalable cloud-native backends for global products.',
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
    '{"x":"https://x.com/lucabianchi"}'::jsonb
  ),
  (
    'spk-emma-johnson',
    'Emma Johnson',
    'UX Designer',
    'Google',
    'Design systems specialist focused on accessibility and motion.',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
    '{"dribbble":"https://dribbble.com/emmajohnson"}'::jsonb
  ),
  (
    'spk-noah-park',
    'Noah Park',
    'Senior Web Engineer',
    'Google Chrome',
    'Works on performance budgets and modern web APIs.',
    'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
    '{"x":"https://x.com/noahpark","github":"https://github.com/noahpark"}'::jsonb
  ),
  (
    'spk-ana-silva',
    'Ana Silva',
    'Developer Relations Engineer',
    'Flutter',
    'Builds cross-platform app experiences and tooling examples.',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    '{"x":"https://x.com/anasilva"}'::jsonb
  ),
  (
    'spk-david-kim',
    'David Kim',
    'Security Engineer',
    'Google',
    'Specializes in app security, auth hardening, and key management.',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    '{"linkedin":"https://linkedin.com/in/davidkim"}'::jsonb
  ),
  (
    'spk-leila-haddad',
    'Leila Haddad',
    'Data Engineer',
    'Google Cloud',
    'Builds analytics pipelines and event-driven data architectures.',
    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
    '{"x":"https://x.com/leilahaddad"}'::jsonb
  ),
  (
    'spk-ryan-cole',
    'Ryan Cole',
    'DevRel Engineer',
    'Firebase',
    'Creates samples around authentication and realtime sync.',
    'https://images.unsplash.com/photo-1504593811423-6dd665756598',
    '{"github":"https://github.com/ryancole"}'::jsonb
  ),
  (
    'spk-olivia-wang',
    'Olivia Wang',
    'Technical Program Manager',
    'Google',
    'Coordinates platform launches across Android, web, and cloud teams.',
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    '{"linkedin":"https://linkedin.com/in/oliviawang"}'::jsonb
  ),
  (
    'spk-carlos-rivera',
    'Carlos Rivera',
    'AI Research Engineer',
    'DeepMind',
    'Bridges applied research into production-ready AI capabilities.',
    'https://images.unsplash.com/photo-1463453091185-61582044d556',
    '{"x":"https://x.com/carlosrivera"}'::jsonb
  )
on conflict (id) do update set
  name = excluded.name,
  role = excluded.role,
  company = excluded.company,
  bio = excluded.bio,
  photo_url = excluded.photo_url,
  social_links = excluded.social_links;

insert into public.sessions (
  id, title, description, start_time, end_time, duration, room, day, track, type, level, speaker_ids, capacity, registered, tags, livestream_url, slides_url, updated_at
)
values
  (
    'sess-day1-keynote-future-ai',
    'Opening Keynote: The Next Wave of AI',
    'Conference kickoff with product updates and platform roadmap.',
    '2026-05-20T09:00:00Z',
    '2026-05-20T10:00:00Z',
    '60m',
    'Main Stage',
    1,
    'AI_ML',
    'KEYNOTE',
    'BEGINNER',
    array['spk-sara-chen','spk-carlos-rivera','spk-olivia-wang']::text[],
    4000,
    3890,
    array['keynote','ai','roadmap']::text[],
    'https://youtube.com/live/mobilemeetsmobile-day1-keynote',
    null,
    now()
  ),
  (
    'sess-day1-android-state',
    'State of Android Development',
    'Best practices for architecture, tooling, and performance in 2026.',
    '2026-05-20T10:30:00Z',
    '2026-05-20T11:15:00Z',
    '45m',
    'Android Stage',
    1,
    'ANDROID',
    'SESSION',
    'INTERMEDIATE',
    array['spk-miguel-ortiz']::text[],
    600,
    570,
    array['android','jetpack','performance']::text[],
    null,
    'https://speakerdeck.com/mobilemeetsmobile/android-2026',
    now()
  ),
  (
    'sess-day1-firebase-auth',
    'Firebase Auth for Multi-Platform Apps',
    'Design secure authentication flows across Android, iOS, and web.',
    '2026-05-20T11:30:00Z',
    '2026-05-20T12:15:00Z',
    '45m',
    'Firebase Hub',
    1,
    'FIREBASE',
    'SESSION',
    'BEGINNER',
    array['spk-priya-nair','spk-ryan-cole']::text[],
    450,
    410,
    array['firebase','auth','kmm']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day1-web-core-web-vitals',
    'Web Performance at Scale',
    'Advanced tuning strategies for Core Web Vitals in large apps.',
    '2026-05-20T13:30:00Z',
    '2026-05-20T14:15:00Z',
    '45m',
    'Web Stage',
    1,
    'WEB',
    'SESSION',
    'ADVANCED',
    array['spk-noah-park']::text[],
    380,
    360,
    array['web','performance','cwv']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day1-cloud-observability',
    'Cloud Observability for Mobile Backends',
    'Metrics, traces, and cost-aware dashboards for backend services.',
    '2026-05-20T14:30:00Z',
    '2026-05-20T15:15:00Z',
    '45m',
    'Cloud Arena',
    1,
    'CLOUD',
    'SESSION',
    'INTERMEDIATE',
    array['spk-luca-bianchi','spk-leila-haddad']::text[],
    420,
    390,
    array['cloud','observability','backend']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day1-flutter-workshop-state',
    'Flutter Workshop: Predictable State Management',
    'Hands-on workshop building a production-ready app module.',
    '2026-05-20T15:30:00Z',
    '2026-05-20T17:00:00Z',
    '90m',
    'Lab 2',
    1,
    'FLUTTER',
    'WORKSHOP',
    'INTERMEDIATE',
    array['spk-ana-silva']::text[],
    120,
    120,
    array['flutter','workshop','state-management']::text[],
    null,
    'https://github.com/mobilemeetsmobile/flutter-workshop-2026',
    now()
  ),
  (
    'sess-day1-design-system',
    'Design Systems That Scale',
    'Practical patterns for tokens, theming, and accessibility.',
    '2026-05-20T17:15:00Z',
    '2026-05-20T18:00:00Z',
    '45m',
    'Design Studio',
    1,
    'DESIGN',
    'SESSION',
    'INTERMEDIATE',
    array['spk-emma-johnson']::text[],
    300,
    265,
    array['design-system','accessibility','tokens']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day2-keynote-cloud-native',
    'Day 2 Keynote: Cloud Native Everywhere',
    'Platform vision for cloud-native developer workflows.',
    '2026-05-21T09:00:00Z',
    '2026-05-21T10:00:00Z',
    '60m',
    'Main Stage',
    2,
    'CLOUD',
    'KEYNOTE',
    'BEGINNER',
    array['spk-luca-bianchi','spk-olivia-wang']::text[],
    4000,
    3720,
    array['keynote','cloud']::text[],
    'https://youtube.com/live/mobilemeetsmobile-day2-keynote',
    null,
    now()
  ),
  (
    'sess-day2-ai-rag-android',
    'Building On-Device RAG Experiences',
    'Combine local and remote inference pipelines for mobile AI.',
    '2026-05-21T10:30:00Z',
    '2026-05-21T11:15:00Z',
    '45m',
    'AI Stage',
    2,
    'AI_ML',
    'SESSION',
    'ADVANCED',
    array['spk-sara-chen','spk-carlos-rivera']::text[],
    500,
    500,
    array['ai','rag','mobile']::text[],
    null,
    'https://speakerdeck.com/mobilemeetsmobile/rag-mobile-2026',
    now()
  ),
  (
    'sess-day2-android-compose-lab',
    'Compose Performance Lab',
    'Measure and improve jank, startup, and memory use in Compose apps.',
    '2026-05-21T11:30:00Z',
    '2026-05-21T13:00:00Z',
    '90m',
    'Lab 1',
    2,
    'ANDROID',
    'CODELAB',
    'ADVANCED',
    array['spk-miguel-ortiz']::text[],
    140,
    135,
    array['android','compose','codelab']::text[],
    null,
    'https://github.com/mobilemeetsmobile/compose-performance-lab',
    now()
  ),
  (
    'sess-day2-firebase-realtime',
    'Realtime Collaboration with Firebase',
    'Implement collaborative editing and presence in minutes.',
    '2026-05-21T13:30:00Z',
    '2026-05-21T14:15:00Z',
    '45m',
    'Firebase Hub',
    2,
    'FIREBASE',
    'SESSION',
    'BEGINNER',
    array['spk-priya-nair','spk-ryan-cole']::text[],
    450,
    430,
    array['firebase','realtime','collaboration']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day2-web-ai-agents',
    'AI Agents in the Browser',
    'Securely orchestrate browser-native AI workflows.',
    '2026-05-21T14:30:00Z',
    '2026-05-21T15:15:00Z',
    '45m',
    'Web Stage',
    2,
    'WEB',
    'SESSION',
    'INTERMEDIATE',
    array['spk-noah-park']::text[],
    360,
    340,
    array['web','ai','agents']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day2-design-motion',
    'Motion Systems for Product Teams',
    'How to define motion primitives and enforce consistency at scale.',
    '2026-05-21T15:30:00Z',
    '2026-05-21T16:15:00Z',
    '45m',
    'Design Studio',
    2,
    'DESIGN',
    'SESSION',
    'INTERMEDIATE',
    array['spk-emma-johnson']::text[],
    280,
    248,
    array['design','motion','ux']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day2-office-hours-security',
    'Office Hours: App Security Review',
    'Bring your architecture questions and threat models.',
    '2026-05-21T16:30:00Z',
    '2026-05-21T17:30:00Z',
    '60m',
    'Mentor Lounge',
    2,
    'CLOUD',
    'OFFICE_HOURS',
    'INTERMEDIATE',
    array['spk-david-kim']::text[],
    80,
    62,
    array['security','office-hours']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day3-keynote-dev-exp',
    'Day 3 Keynote: Developer Experience',
    'Tools and workflows that reduce cognitive load across teams.',
    '2026-05-22T09:00:00Z',
    '2026-05-22T10:00:00Z',
    '60m',
    'Main Stage',
    3,
    'ANDROID',
    'KEYNOTE',
    'BEGINNER',
    array['spk-olivia-wang','spk-miguel-ortiz']::text[],
    4000,
    3660,
    array['keynote','dx']::text[],
    'https://youtube.com/live/mobilemeetsmobile-day3-keynote',
    null,
    now()
  ),
  (
    'sess-day3-kmm-architecture',
    'KMM Architecture for Offline-First Apps',
    'Patterns for shared domain logic, sync orchestration, and caching.',
    '2026-05-22T10:30:00Z',
    '2026-05-22T11:15:00Z',
    '45m',
    'Android Stage',
    3,
    'ANDROID',
    'SESSION',
    'ADVANCED',
    array['spk-miguel-ortiz','spk-priya-nair']::text[],
    520,
    512,
    array['kmm','offline-first','architecture']::text[],
    null,
    'https://speakerdeck.com/mobilemeetsmobile/kmm-offline-first',
    now()
  ),
  (
    'sess-day3-cloud-costs',
    'Cloud Cost Controls for Startups',
    'Practical budgets, alerts, and architecture tradeoffs.',
    '2026-05-22T11:30:00Z',
    '2026-05-22T12:15:00Z',
    '45m',
    'Cloud Arena',
    3,
    'CLOUD',
    'SESSION',
    'BEGINNER',
    array['spk-luca-bianchi','spk-leila-haddad']::text[],
    350,
    301,
    array['cloud','finops']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day3-ai-eval-codelab',
    'Codelab: Evaluation Pipelines for GenAI',
    'Build automated evaluation loops for quality and safety.',
    '2026-05-22T13:30:00Z',
    '2026-05-22T15:00:00Z',
    '90m',
    'Lab 3',
    3,
    'AI_ML',
    'CODELAB',
    'ADVANCED',
    array['spk-sara-chen','spk-carlos-rivera']::text[],
    100,
    98,
    array['ai','genai','codelab','evaluation']::text[],
    null,
    'https://github.com/mobilemeetsmobile/genai-eval-codelab',
    now()
  ),
  (
    'sess-day3-web-pwa',
    'From SPA to Installable PWA',
    'Ship offline support, push, and install prompts correctly.',
    '2026-05-22T15:15:00Z',
    '2026-05-22T16:00:00Z',
    '45m',
    'Web Stage',
    3,
    'WEB',
    'SESSION',
    'INTERMEDIATE',
    array['spk-noah-park']::text[],
    320,
    295,
    array['web','pwa','offline']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day3-flutter-design-systems',
    'Flutter + Design Tokens End-to-End',
    'Integrate design tokens into a scalable Flutter UI pipeline.',
    '2026-05-22T16:15:00Z',
    '2026-05-22T17:00:00Z',
    '45m',
    'Flutter Stage',
    3,
    'FLUTTER',
    'SESSION',
    'INTERMEDIATE',
    array['spk-ana-silva','spk-emma-johnson']::text[],
    290,
    276,
    array['flutter','design-system','tokens']::text[],
    null,
    null,
    now()
  ),
  (
    'sess-day3-office-hours-firebase',
    'Office Hours: Firebase Data Modeling',
    'Review data models, indexes, and sync strategies with experts.',
    '2026-05-22T17:15:00Z',
    '2026-05-22T18:00:00Z',
    '45m',
    'Mentor Lounge',
    3,
    'FIREBASE',
    'OFFICE_HOURS',
    'BEGINNER',
    array['spk-ryan-cole','spk-priya-nair']::text[],
    90,
    75,
    array['firebase','office-hours','data-modeling']::text[],
    null,
    null,
    now()
  )
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  duration = excluded.duration,
  room = excluded.room,
  day = excluded.day,
  track = excluded.track,
  type = excluded.type,
  level = excluded.level,
  speaker_ids = excluded.speaker_ids,
  capacity = excluded.capacity,
  registered = excluded.registered,
  tags = excluded.tags,
  livestream_url = excluded.livestream_url,
  slides_url = excluded.slides_url,
  updated_at = now();
